
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.cake]

		[types.cake.youkaishomecoming]
			red_velvet_cake = true

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

		[types.cake.blue_skies]
			comet_berry_pie = true

		[types.cake.enigmaticlegacy]
			cosmic_cake = true

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.blue_skies]
			crystallized = true
			crescent_fruit = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.chipped]
			apple_acacia = true
			cherry_acacia = true
			dead_acacia = true
			frosted_acacia = true
			golden_acacia = true
			golden_cherry_acacia = true
			magenta_flower_acacia = true
			orange_acacia = true
			red_acacia = true
			white_flower_acacia = true
			apple_birch = true
			cherry_birch = true
			dead_birch = true
			frosted_birch = true
			golden_birch = true
			golden_cherry_birch = true
			magenta_flower_birch = true
			orange_birch = true
			red_birch = true
			white_flower_birch = true
			apple_dark_oak = true
			cherry_dark_oak = true
			dead_dark_oak = true
			frosted_dark_oak = true
			golden_dark_oak = true
			golden_cherry_dark_oak = true
			magenta_flower_dark_oak = true
			orange_dark_oak = true
			red_dark_oak = true
			white_flower_dark_oak = true
			apple_jungle = true
			cherry_jungle = true
			dead_jungle = true
			frosted_jungle = true
			golden_jungle = true
			golden_cherry_jungle = true
			magenta_flower_jungle = true
			orange_jungle = true
			red_jungle = true
			white_flower_jungle = true
			apple_oak = true
			cherry_oak = true
			dead_oak = true
			frosted_oak = true
			golden_oak = true
			golden_cherry_oak = true
			magenta_flower_oak = true
			orange_oak = true
			red_oak = true
			white_flower_oak = true
			apple_spruce = true
			cherry_spruce = true
			dead_spruce = true
			frosted_spruce = true
			golden_spruce = true
			golden_cherry_spruce = true
			magenta_flower_spruce = true
			orange_spruce = true
			red_spruce = true
			white_flower_spruce = true
			golden_apple_acacia = true
			golden_apple_birch = true
			golden_apple_dark_oak = true
			golden_apple_jungle = true
			golden_apple_oak = true
			golden_apple_spruce = true

		[types.leaves_type.betternether]
			willow = true
			rubeus = true
			anchor_tree = true
			nether_sakura = true

		[types.leaves_type.betterend]
			pythadendron = true
			lacugrove = true
			dragon_tree = true
			tenanea = true
			lucernia = true

		[types.leaves_type.edenring]
			auritis = true

		[types.leaves_type.fruitfulfun]
			cherry = true
			redlove = true
			pomegranate = true
			tangerine = true
			lime = true
			citron = true
			pomelo = true
			orange = true
			lemon = true
			grapefruit = true
			apple = true

		[types.leaves_type.mythicbotany]
			dreamwood = true

		[types.leaves_type.occultism]
			otherworld = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.goety]
			hardened = true
			rotten = true
			windswept = true

		[types.leaves_type.thermal]
			rubberwood = true

		[types.leaves_type.allthemodium]
			ancient = true
			demonic = true
			soul = true

		[types.leaves_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true
			palo_verde = true
			araucaria = true
			ripe_baobab = true
			flowering_baobab = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			ripe_orchard = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			yucca = true
			ripe_yucca = true
			flowering_yucca = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			silver_maple = true
			green_apple_skyris = true
			flowering_skyris = true
			flowering_ironwood = true
			white_sakura = true
			yellow_sakura = true
			yellow_birch = true
			yellow_spruce = true
			firecracker = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.deep_aether]
			roseroot = true
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.aether_redux]
			blightwillow = true
			glacia = true
			purple_glacia = true
			gilded_oak = true
			blighted_skyroot = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.vinery]
			grapevine = true
			dark_cherry = true
			apple = true

		[types.leaves_type.meadow]
			pine = true

		[types.leaves_type.beachparty]
			palm = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.forbidden_arcanus]
			aurum = true
			nuggety_aurum = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

	[types.wood_type]

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.blue_skies]
			crystallized = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.betternether]
			nether_reed = true
			stalagnate = true
			willow = true
			wart = true
			rubeus = true
			mushroom_fir = true
			nether_mushroom = true
			anchor_tree = true
			nether_sakura = true

		[types.wood_type.betterend]
			mossy_glowshroom = true
			pythadendron = true
			end_lotus = true
			lacugrove = true
			dragon_tree = true
			tenanea = true
			helix_tree = true
			umbrella_tree = true
			jellyshroom = true
			lucernia = true

		[types.wood_type.edenring]
			auritis = true
			balloon_mushroom = true
			pulse_tree = true
			brain_tree = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.fruitfulfun]
			redlove = true
			citrus = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.goety]
			haunted = true
			rotten = true
			windswept = true

		[types.wood_type.thermal]
			rubberwood = true

		[types.wood_type.allthemodium]
			demonic = true
			soul = true

		[types.wood_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.aether_redux]
			fieldsproot = true
			blightwillow = true
			cloudcap = true
			jellyshroom = true
			crystal = true
			glacia = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.vinery]
			dark_cherry = true

		[types.wood_type.meadow]
			pine = true

		[types.wood_type.beachparty]
			palm = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			aurum = true
			edelwood = true

	[types.stone_type]

		[types.stone_type.betternether]
			blue_obsidian = true

		[types.stone_type.betterend]
			flavolite = true
			violecite = true
			sulphuric_rock = true
			virid_jadestone = true
			azure_jadestone = true
			sandy_jadestone = true
			umbralith = true
			smaragdant_crystal = true

		[types.stone_type.botania]
			livingrock = true

		[types.stone_type.ad_astra]
			moon_stone = true
			mars_stone = true
			mercury_stone = true
			venus_stone = true
			venus_sandstone = true
			glacio_stone = true
			permafrost = true

		[types.stone_type.chipped]
			crying_obsidian = true
			mud_bricks = true
			angled_mud_bricks = true
			angry_mud = true
			arrow_mud = true
			button_mud = true
			carved_mud = true
			centered_mud = true
			chiseled_mud = true
			cracked_mud_bricks = true
			crunched_mud_bricks = true
			crying_mud = true
			cut_blank_mud = true
			double_mud_bricks = true
			duh_mud = true
			engraved_mud = true
			etched_mud_bricks = true
			eye_mud = true
			fancy_mud = true
			fancy_chiseled_mud = true
			glad_mud = true
			heart_mud = true
			horned_mud = true
			inlayed_mud = true
			keyhole_mud = true
			large_tiled_mud = true
			leaning_mud = true
			mini_tiled_mud = true
			offset_mud_bricks = true
			pancake_mud = true
			panelled_mud = true
			placed_mud = true
			polished_mud = true
			quad_mud = true
			rough_mud = true
			rough_panelled_mud = true
			rune_mud = true
			sad_mud = true
			sigil_mud = true
			small_mud_bricks = true
			smooth_mud = true
			smooth_ringed_mud = true
			smoothed_double_inlayed_mud = true
			spiral_mud = true
			stacked_mud_bricks = true
			star_mud = true
			symbol_mud = true
			thick_inlayed_mud = true
			tiled_mud_bricks = true
			tiny_mud_bricks = true
			tiny_layered_mud_bricks = true
			unamused_mud = true
			vertical_cut_mud = true
			vertical_disordered_mud_bricks = true
			bordered_mud = true
			brick_bordered_mud = true
			edged_mud_bricks = true
			hard_mud = true
			scaly_mud = true
			tiled_bordered_mud = true
			massive_mud_bricks = true
			diamond_mud_bricks = true
			loreful_mud = true

		[types.stone_type.undergarden]
			depthrock = true
			shiverstone = true
			tremblecrust = true

		[types.stone_type.mysticalagriculture]
			soulstone = true

		[types.stone_type.goety]
			shade_stone = true
			highrock = true
			siltstone = true
			chiseled_siltstone = true

		[types.stone_type.allthemodium]
			ancient_stone = true

		[types.stone_type.blue_skies]
			polished_brumble = true

		[types.stone_type.biomeswevegone]
			dacite = true
			red_rock = true

		[types.stone_type.aether]
			holystone = true

		[types.stone_type.deep_aether]
			aseterite = true
			aether_mud = true

		[types.stone_type.aether_redux]
			sentrite = true

		[types.stone_type.iceandfire]
			dread_stone = true

		[types.stone_type.deeperdarker]
			sculk_stone = true
			sculk_grime = true
			gloomslate = true

		[types.stone_type.meadow]
			limestone = true

		[types.stone_type.create]
			cut_granite = true
			cut_diorite = true
			cut_andesite = true
			cut_calcite = true
			cut_dripstone = true
			cut_deepslate = true
			cut_tuff = true
			cut_asurine = true
			cut_crimsite = true
			cut_limestone = true
			cut_ochrum = true
			cut_scoria = true
			cut_scorchia = true
			cut_veridium = true

		[types.stone_type.alexscaves]
			galena = true
			radrock = true
			abyssmarine = true
			guanostone = true

		[types.stone_type.forbidden_arcanus]
			polished_darkstone = true

		[types.stone_type.quark]
			soul_sandstone = true
			permafrost = true
			limestone = true
			jasper = true
			shale = true
			myalite = true

		[types.stone_type.supplementaries]
			ash = true

#Disables specific entries
[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

	[entries.wood_type]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			dining_bench = true
			drawer = true
			side_table = true
			couch = true
			table = true
			chair = true
			shelf = true
			cupboard = true
			bench = true
			pillar_trim = true
			nightstand = true

		[entries.wood_type.chipped]
			fine_planks = true
			checkered_trapdoor = true
			overgrown_trapdoor = true
			overgrown_door = true
			windowed_door = true
			tiled_door = true
			classic_trapdoor = true
			circle_glass = true
			pegged_planks = true
			torch = true
			secret_door = true
			smooth_planks = true
			screen_door = true
			bared_glass = true
			ornate_bared_glass = true
			hewn_planks = true
			crossed_planks = true
			beach_door = true
			fine_vertical_planks = true
			cross_laced_planks = true
			diamond_bordered_glass = true
			railed_planks = true
			planks_mosaic = true
			distorted_trapdoor = true
			iron_barred_trapdoor = true
			circle_glass_pane = true
			versailles_planks = true
			whirlwind_planks = true
			large_diamond_glass_pane = true
			framed_planks = true
			square_glass = true
			vined_trapdoor = true
			barrel = true
			woven_glass = true
			detailed_planks = true
			woven_trapdoor = true
			cobweb_trapdoor = true
			gated_door = true
			supported_door = true
			barred_trapdoor = true
			line_bared_glass_pane = true
			horizontal_lined_glass_pane = true
			airy_trapdoor = true
			line_bared_glass = true
			slanted_planks = true
			barred_door = true
			suspicious_trapdoor = true
			herringbone_planks = true
			pressed_door = true
			planks_panel = true
			vertically_railed_planks = true
			bared_glass_pane = true
			diamond_bordered_glass_pane = true
			solid_trapdoor = true
			tiled_planks = true
			boarded_door = true
			dual_paneled_door = true
			square_glass_pane = true
			meshed_trapdoor = true
			thin_planks = true
			fancy_trapdoor = true
			paper_door = true
			warted_trapdoor = true
			basket_woven_planks = true
			enclosed_planks = true
			double_herringbone_planks = true
			crated_planks = true
			horizontal_lined_glass = true
			natural_planks = true
			classic_windowed_trapdoor = true
			brick_bond_planks = true
			wickered_planks = true
			bordered_glass_pane = true
			sliding_door = true
			heavy_trapdoor = true
			bordered_glass = true
			laced_planks = true
			boxed_planks = true
			reinforced_crate = true
			large_diamond_glass = true
			snowflake_glass_pane = true
			bricky_planks = true
			slotted_trapdoor = true
			shack_door = true
			polished_planks = true
			ornate_bared_glass_pane = true
			diagonal_planks = true
			wall_torch = true
			crate = true
			nailed_planks = true
			cornered_planks = true
			shifted_planks = true
			vertical_planks = true
			glass_door = true
			fortified_door = true
			paneled_door = true
			leafy_trapdoor = true
			snowflake_glass = true
			heavy_door = true
			pointless_trapdoor = true
			stacked_planks = true
			planks_shavings = true
			twisted_trapdoor = true
			diamond_planks = true
			woven_glass_pane = true
			windowed_trapdoor = true
			tile_windowed_door = true
			golden_barred_trapdoor = true

		[entries.wood_type.quark]
			vertical_planks = true
			ladder = true
			post = true
			trapped_chest = true
			chest = true
			hollow_log = true
			bookshelf = true
			stripped_post = true

		[entries.wood_type.twilightforest]
			banister = true

		[entries.wood_type.decorative_blocks]
			seat = true
			palisade = true
			beam = true
			support = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.create]
			window_pane = true
			window = true

